I worked on the Submit Page using HTML
Dufuna-CodeCamp/Niger20-Hack1 pull request #3
Opened 2020-08-01 14:20 UTC by Cynthia-Berry

## `I worked on the Submit Page using HTML`
![submit1](https://user-images.githubusercontent.com/34312453/89103530-6e173e80-d40a-11ea-96bf-f8c54af286ca.PNG)
![submit2](https://user-images.githubusercontent.com/34312453/89103534-6fe10200-d40a-11ea-8b72-cff90fd38655.PNG)

2020-08-01 14:43 UTC, michaelolubajo reviewed
Good job! I like that it goes straight to the point.
For the logo we'll need to link to a single file in an images folder for all 3 pages. 
Also, our nav bars need to have a uniform look. By the way, the image you shared shows a duplication of the links at the top.
We're almost there.
Well done

2020-08-01 15:24 UTC, Cynthia-Berry commented
@michaelolubajo I added you as a reviewer. You can approve so Yemi can Merge the post.
Hopeful by the end of today we will get other Team members' work and effect changes where necessary.

Thank You.

2020-08-01 15:45 UTC, michaelolubajo approved these changes

2020-08-01 16:47 UTC, yemexx1 requested changes
Nice work! Please take a look at inline comments.

Like I mentioned in #2, we can put the html files in the root of the project.

2020-08-01 16:47 UTC, yemexx1 commented on Covid-watch-by-cynthia/submit.html
> +          <textarea name="" id="" cols="100" rows="20"></textarea>
you're missing the name here, could you add it?

2020-08-01 16:47 UTC, yemexx1 commented on Covid-watch-by-cynthia/submit.html
> +  <title>Submit</title>
Let's make this full - `Submit News`

2020-08-01 16:47 UTC, yemexx1 commented on Covid-watch-by-cynthia/submit.html
> +          <button type="submit">SUBMIT</button>
Let's make submit also title case here.

2020-08-01 19:10 UTC, yemexx1 requested changes
@Cynthia-Berry could you move the image into images folder to align with master?

2020-08-01 19:15 UTC, Cynthia-Berry commented
> @Cynthia-Berry could you move the image into images folder to align with master?

I ran a got fetch but couldn't get Michael's image folder. That's why I have a  `img`  in my PR

2020-08-01 19:50 UTC, michaelolubajo approved these changes

2020-08-02 06:12 UTC, yemexx1 approved these changes

2020-08-02 06:13 UTC, merged